version: "3.7"

services:
  app:
    container_name: "kendi-api"
    build: "./"
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - alpha
    depends_on:
      - postgres

  postgres:
    container_name: postgress
    image: "postgres:12.2-alpine"
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - alpha
networks:
  alpha:
